version: '3'

services:
  signvetapi:
    container_name: signvetapi
    build:
      context: .
      args:
        JAVA_VERSION: 11
    ports:
      - "9599:9599"

  signvetapp:
    container_name: signvetapp
    build:
      context: ./signature-verification  # Directory containing the Angular Dockerfile
    ports:
      - "8080:80"  # Map container port 80 (default for Nginx) to host port 8080
    depends_on:
      - signvetapi
