version: '3'

services:
  spring-boot-app:
    container_name: signature_service
    build:
      context: .  # Directory containing the Spring Boot Dockerfile
      args:
        JAVA_VERSION: 17  # Set the Java version as an argument to be used in Dockerfile
    ports:
      - "8080:8080"  # Map container port 8080 to host port 8080
